### ISSUE TITLE
nfc-tools 403 when building docker image

### ISSUE THREAD

**Issue by charlesvestal** [sorasful/RFID-Mifare-cloner#1]
It seems bintray has shut down - can/ should this be updated?

[+] Building 1.0s (10/21)                                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                              0.0s
 => => transferring dockerfile: 37B                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ubuntu:18.04                                                                                   0.6s
 => [ 1/17] FROM docker.io/library/ubuntu:18.04@sha256:538529c9d229fb55f50e6746b119e899775205d62c0fc1b7e679b30d02ecb6e8                           0.0s
 => [internal] load build context                                                                                                                 0.0s
 => => transferring context: 2.43kB                                                                                                               0.0s
 => CACHED [ 2/17] WORKDIR /tmp                                                                                                                   0.0s
 => CACHED [ 3/17] RUN apt update && apt install -y autoconf pcsc-tools pcscd libpcsclite-dev libpcsclite1 libusb-dev wget build-essential git p  0.0s
 => CACHED [ 4/17] RUN apt-get install -y libpcsclite-dev libpcsclite1 pcsc-tools pcscd                                                           0.0s
 => CACHED [ 5/17] RUN apt-get install -y automake autoconf libtool libusb-dev                                                                    0.0s
 => ERROR [ 6/17] RUN wget http://dl.bintray.com/nfc-tools/sources/libnfc-1.7.1.tar.bz2                                                           0.3s
------                                                                                                                                                 
 > [ 6/17] RUN wget http://dl.bintray.com/nfc-tools/sources/libnfc-1.7.1.tar.bz2:                                                                      
#9 0.250 --2021-05-13 15:12:16--  http://dl.bintray.com/nfc-tools/sources/libnfc-1.7.1.tar.bz2                                                         
#9 0.250 Resolving dl.bintray.com (dl.bintray.com)... 18.158.192.105, 35.156.121.1
#9 0.271 Connecting to dl.bintray.com (dl.bintray.com)|18.158.192.105|:80... connected.
#9 0.285 HTTP request sent, awaiting response... 403 Forbidden
#9 0.298 2021-05-13 15:12:16 ERROR 403: Forbidden.
#9 0.298 
------
executor failed running [/bin/sh -c wget http://dl.bintray.com/nfc-tools/sources/libnfc-1.7.1.tar.bz2]: exit code: 8

**Comment by ruudboon** [comment]
Same here
